import type { Metadata } from 'next'
import './globals.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import { ThemeContextProvider } from '@/context/ThemeContext'
import 'react-toastify/dist/ReactToastify.css';


export const metadata: Metadata = {
  title: 'LinkOn | URL Shortener',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <ThemeContextProvider>
        <body>
          <Navbar/>
          {children}
          <Footer/>
        </body>
      </ThemeContextProvider>
    </html>
  )
}
